### PR TITLE
Add the missing cache files

### PR DESCRIPTION
**Pull request by TuxCoding**

### CODE REVIEW

**Comment by TuxCoding** [comment]
@sgdc3 
>you have the permission to push directly to the repo

Not really.

>remote: Resolving deltas: 100% (28/28), completed with 8 local objects.
To github.com:AuthMe/MaxMindDB-Reader-Gson.git
 ! [remote rejected] authme -> gson (permission denied)

Or here on Github:

>You’re creating a file in a project you don’t have write access to. Submitting a change will create the file in a new branch in your fork games647/MaxMind-DB-Reader-java, so you can send a pull request.

**Comment by sgdc3** [comment]
Fixed, sorry for that. @games647

**Comment by sgdc3** [comment]
Tests are failing on jenkins

**Comment by TuxCoding** [comment]
https://github.com/AuthMe/MaxMindDB-Reader-Gson/blob/76d0a2294801517166a5904982faf298d18dd0e3/.gitmodules#L1-L3

Git submodules are not initialized. Either a `git submodule init` call is required or a maven plugin which does the same.

**Comment by sgdc3** [comment]
Still failing

**Comment by TuxCoding** [comment]
Try that
`git submodule update --init --recursive` 

It's still empty I think it not synced yet.

**Comment by sgdc3** [comment]
Yep that worked

**Pull request merged**
